### ISSUE TITLE
Add additional parameters to packageAfter

### ISSUE THREAD

**Issue by Dydhzo** [matvp91/superstreamer#102]
Hello, I hope this message finds you well. I'd like to suggest a new feature for improving the packageAfter functionality.

**Is your feature request related to a problem? Please describe.**
When working with packageAfter, there's currently no way to specify additional parameters such as defaultLanguage. This limits the flexibility and ease of use when transcoding and packaging content, especially in multilingual environments.

**Describe the solution you'd like**
I'd like to see additional parameters for packageAfter, which would allow for more comprehensive and flexible configuration. For example, the ability to specify defaultLanguage would be particularly useful.

**Describe alternatives you've considered**
Currently, we have to handle language settings separately or in post-processing, which is less efficient and more prone to errors.

**Additional context**
Here's an example of how this could be implemented in the API call:

```
curl --request POST \
  --url https://stitcher-superstreamer.domain.com/transcode \
  --header 'Content-Type: application/json' \
  --data '{
  "inputs": [
    {
      "type": "video",
      "path": ""
    }
  ],
  "streams": [
    {
      "type": "video",
      "codec": "h264",
      "height": 1080,
      "bitrate": 4000000,
      "framerate": 30
    }
  ],
  "segmentSize": 6,
  "packageAfter": true,
  "defaultLanguage": "eng"
}'
```

This enhancement would streamline the workflow, especially when working on large-scale projects where each team member needs to run their commands efficiently without getting lost in the process.

**Comment by matvp91** [comment]
What if we'd drop `packageAfter` and provide a package property instead that takes the same payload as the `/transcode` endpoint?

**Comment by Dydhzo** [comment]
Yes, it's a good idea because, in the end, the result will be the same - subtitles will always be defined by default and the same with audio

**Comment by Dydhzo** [comment]
Alright, thank you! I'm looking forward to it—it'll save a bit of time
