### ISSUE TITLE
Enable default subtitles

### ISSUE THREAD

**Issue by Dydhzo** [matvp91/superstreamer#87]
Hello I have a request here are the explanations :

**Describe the feature request**
I would like a feature to automatically activate subtitles by default when playing a video file.

**Expected behavior**
Subtitles should be enabled by default in the player settings.

**Additional context**
Currently, when playing the following configurations, subtitles are not enabled by default. This feature would improve user experience by ensuring subtitles are always visible unless manually turned off.

**Comment by matvp91** [comment]
Support for `DEFAULT=YES` in `EXT-X-MEDIA` tags is added in 8018702. The alpha build is published on Docker (`superstreamerapp/{package}:alpha`). When packaging, you can specify a default language:

```
{
  "assetId": "36446000-9ef7-4bf0-8147-c45139cf22d6",
  "defaultLanguage": "fra"
}
```

Beware that this is an alpha build and the API is subjective to change until it lands into a final release.

**Comment by matvp91** [comment]
`defaultLanguage` has been dropped in favor of `language`, which you can provide to the package endpoint. There's no longer a split between audio and text, language merely means "we'll prefer to force this language upon the viewer" and the system will match this as best as possible, prioritizing audio over text.

**Comment by Dydhzo** [comment]
Alright, thank you. I'll test it
